### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by survient** [dtaht/sch_cake#101]
I'd like to package sch_cake as an RPM on RPMFusion for Fedora but without a license attributed to this project it will be difficult. I realize there is a license on the tc-adv repo but it's a bit of a weak reference and would really help out if the license was also added to this repo.

**Comment by chromi** [comment]
> On 7 Jul, 2018, at 10:21 pm, survient <notifications@github.com> wrote:
> 
> I'd like to package sch_cake as an RPM on RPMFusion for Fedora but without a license attributed to this project it will be difficult. I realize there is a license on the tc-adv repo but it's a bit of a weak reference and would really help out if the license was also added to this repo.

As this is a kernel module, the licence is specified in the standard way for such things, using a macro at the bottom of sch_cake.c.  Is that not sufficient?

 - Jonathan Morton

**Comment by survient** [comment]
Sorry @chromi, I completely missed that. I'm new to this but just trying to make sure I cover my bases, thanks for the clarification this helps.
