### ISSUE TITLE
Bandwidth limiter not working 

### ISSUE THREAD

**Issue by RubenKelevra** [dtaht/sch_cake#106]
On my machine, the bandwidth limiter is currently non-operational. I'm not quite sure what leads to this issue, though.

I'm running Arch Linux with the LTS kernel (4.14.68) and using the AUR package iproute2-cake (r4242.a55119d1-1) and sch_cake-dkms (r472.eb15399-1).

When I use the man page example

`tc qdisc add root dev eth0 cake bandwidth 100Mbit ethernet`

or any other parameter I tried, the _capacity estimate_ is always at `6755Tbit` - which makes no sense to me.

I'm not sure how to debug this, but I let the machine running in this state (maybe a reboot would fix this?)

**Comment by chromi** [comment]
> On 10 Sep, 2018, at 12:42 am, @RubenKelevra <notifications@github.com> wrote:
> 
> or any other parameter I tried, the capacity estimate is always at 6755Tbit - which makes no sense to me.

It sounds very much like the iproute2 version is mismatched.  There was a major compatibility break at some point.

I recommend you ask AUR or whoever is responsible to update both packages to match the current code.

 - Jonathan Morton

**Comment by RubenKelevra** [comment]
Thanks for the fast response. This info was very helpful. Looks like the sch_cake package haven't had the propper version, so the last update wasn't pulled from the AUR.

Maybe I'm the one to blame for this, I'm not sure.

Anyway, the issue is fixed now:

```
qdisc cake 8012: root refcnt 2 bandwidth 100Mbit diffserv3 triple-isolate split-gso rtt 100.0ms noatm overhead 38 mpu 84 
 Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
 memory used: 0b of 5000000b
 capacity estimate: 100Mbit
 min/max network layer size:        65535 /       0
 min/max overhead-adjusted size:    65535 /       0
 average network hdr offset:            0

                   Bulk  Best Effort        Voice
  thresh       6250Kbit      100Mbit       25Mbit
  target          5.0ms        5.0ms        5.0ms
  interval      100.0ms      100.0ms      100.0ms
  pk_delay          0us          0us          0us
  av_delay          0us          0us          0us
  sp_delay          0us          0us          0us
  backlog            0b           0b           0b
  pkts                0            0            0
  bytes               0            0            0
  way_inds            0            0            0
  way_miss            0            0            0
  way_cols            0            0            0
  drops               0            0            0
  marks               0            0            0
  ack_drop            0            0            0
  sp_flows            0            0            0
  bk_flows            0            0            0
  un_flows            0            0            0
  max_len             0            0            0
  quantum           300         1514          762
```

Thanks a lot!
