### ISSUE TITLE
Hung up with sqm-script cake layer

### ISSUE THREAD

**Issue by yutayu** [dtaht/sch_cake#109]
uname -a
Linux raspberrypi 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux

no syslog sorry.

**Comment by chromi** [comment]
> On 26 Oct, 2018, at 2:54 pm, yutayu <notifications@github.com> wrote:
> 
> Linux raspberrypi 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux

Looks like a distro kernel with a lot of patches relative to upstream.  It's very hard to debug such things, especially with no details or debugging information.  Better to send a bug report to the distro maintainers.

 - Jonathan Morton

**Comment by yutayu** [comment]
ah special kernel okay.
:)
Thank you for your reply. Morton.
