### ISSUE TITLE
Make your internet not slow. or Make your internet latency be short.

### ISSUE THREAD

**Issue by yutayu** [dtaht/sch_cake#111]
This subject is correct cake qdisc benefit I think.
I recommand cake qdisc friends with saying [ this makes your internet faster ] ,
he says [ enough ] :P

I made advertising past days.
Some says [ make your internet fast ] , this is not lie but not benefit.
I think .

Anyway , Great jobs . thanks.

**Comment by thagabe** [comment]
How is this an issue?

**Comment by yutayu** [comment]
> How is this an issue?

Is this title lies or not  is issue :P

**Comment by chromi** [comment]
It's difficult to determine what you're actually asking here.  Clearly English is not your native language, but could you try to explain more clearly?

**Comment by xnoreq** [comment]
A speed up can be perceived (depending on the usage scenario) when you
compare a shaped connection to an unshaped one but there is no actual speed
increase.

To the contrary, you often have to configure lower rates than maximally
possible in order to become the bottleneck that then has control.


> How is this an issue?
>
> Is this title lies or not is issue :P
>
> —

**Comment by chromi** [comment]
> On 7 Feb, 2019, at 7:00 pm, xnoreq <notifications@github.com> wrote:
> 
> A speed up can be perceived (depending on the usage scenario) when you
> compare a shaped connection to an unshaped one but there is no actual speed
> increase.

Or, more precisely, there are two different kinds of "fast":

1: High Throughput.  This is needed to play a high-definition video without buffering, or to download a large game update in a reasonable amount of time.

2: Short Delay.  This is needed while playing the game (aka "ping time"), but also for simply browsing Web pages.

It's the difference between a Shinkansen that runs twice an hour and on which you need to book a seat in advance, versus a local commuter train that runs every 5 minutes, and you can just turn up and get on.  You take the former if you need to go a very long way; you take the latter if you just need to get into town.

A dumb FIFO, as implemented in most network interfaces' hardware, tends to maximise "type 1" speed at the expense of "type 2" speed.  The moment a Shinkansen service is scheduled, it barges all the commuter trains out of the way.  Real railways don't work that way, and for good reason.

By inserting a much smarter and more sophisticated queue, we get a lot more "type 2" speed at the expense of losing a little "type 1" speed - but only a very little is lost.  So the commuter train gets its own tracks and stays out of the Shinkansen's way, and both can flow smoothly.

 - Jonathan Morton

**Comment by moeller0** [comment]
There is a nice description of the issue in [https://docs.google.com/a/chromium.org/viewer?a=v&pid=sites&srcid=Y2hyb21pdW0ub3JnfGRldnxneDoxMzcyOWI1N2I4YzI3NzE2](url)

**Comment by yutayu** [comment]
> There is a nice description of the issue in [https://docs.google.com/a/chromium.org/viewer?a=v&pid=sites&srcid=Y2hyb21pdW0ub3JnfGRldnxneDoxMzcyOWI1N2I4YzI3NzE2](url)

moeeee, yes that it is . 
I mean , Faster ( bandwidth )  is not important.
And I wanted to let  add it or replace it on cake title.

**Comment by richb-hanover** [comment]
> There is a nice description of the issue in https://docs.google.com/a/chromium.org/viewer?a=v&pid=sites&srcid=Y2hyb21pdW0ub3JnfGRldnxneDoxMzcyOWI1N2I4YzI3NzE2

_Corrected the URL_
