### ISSUE TITLE
Cake for multi pppoe and ip to ip shaper

### ISSUE THREAD

**Issue by micron10** [dtaht/sch_cake#112]
Hi 
I try to use cake in test system with 

eth0 - uplink Interne
eth1 - customer (with dhcp and static ips) on bridge with 4 vlans
eth2 - pppoe cuscome (20 users)

eth0 - have real ip

eth1 and eth2 (pppoe) have 192.168.x.x/x

And i have 3 speed class

3mbit/3mbit (Up/Down)
7mbit/7mbit (Up/Down)
10mbit/10mbit (Up/Down)

i what to work with cake and shape upload/download from to users 
Cake not support classid and this stop my test 

i try to replace imq/ifb with cake for more stable networking

Any help ?

Thanks

**Comment by dtaht** [comment]
Well, simplicity is your first option with cake. I'd first correctly regulate eth0 with cake + the sqm-scripts for inbound and outbound. Doing speed classes as you desire is not what cake is about, it is about offering fairness to hosts and flows, so just slamming cake again on eth1 and eth2 will give you that. If you want speed tiers on eth1 and eth2 on a per IP basis you are better off constructing something that is htb + fq_codel based on those interfaces.
