### ISSUE TITLE
What is tin_quantum_prio used for?  Looks unused

### ISSUE THREAD

**Issue by ldir-EDB0** [dtaht/sch_cake#121]
As per the title I can't find any code that actually uses the tin_quantum_prio variable.

I can find tin_quantum_band used in the tin selection algorithm.  We go to some effort to set tin_quantum_prio but I can't find where it's used.

**Comment by chromi** [comment]
> On 16 Dec, 2019, at 9:58 pm, Kevin Darbyshire-Bryant <notifications@github.com> wrote:
> 
> As per the title I can't find any code that actually uses the tin_quantum_prio variable.
> 
> I can find tin_quantum_band used in the tin selection algorithm. We go to some effort to set tin_quantum_prio but I can't find where it's used.

I think it's a leftover from an earlier implementation of the Diffserv tins.  Now it's done entirely through the shapers' state, except when the shaper is disabled completely.

So it would actually be reasonable to delete that variable and all references to it, as long as tin_quantum_band is still valid.

 - Jonathan Morton

**Comment by ldir-EDB0** [comment]
OK - I'll drop the variable and check nothing goes bang :-)
