### ISSUE TITLE
Is via-ethernet option deleted?

### ISSUE THREAD

**Issue by yutayu** [dtaht/sch_cake#129]
Does that mean we don't need to bother minus ethernet overhead 14 from ppp overhead?

**Comment by chromi** [comment]
> On 6 Feb, 2020, at 4:34 am, yutayu <notifications@github.com> wrote:
> 
> That means we don't need to bother minus ethernet overhead 14 from ppp overhead?

The overhead is now calculated from the underlying IP packet size, and not from the raw reported packet size which could "sometimes" include Ethernet framing.  The latter was the reason for the via-ethernet option, which is therefore no longer needed.

 - Jonathan Morton

**Comment by yutayu** [comment]
@chromi I got meaning.Thanks.:)

**Comment by yutayu** [comment]
In addition , Does it needs to set mpu behind LAN? 
My recognization is ,
When settled bandwidth is for internet , so we don't need to set mpu.
When settled bandwidth is for ethernet , we need to consider mpu.

**Comment by yutayu** [comment]
pi@raspberrypi:~ $ tc -s qdisc show dev eth0
qdisc cake 8006: root refcnt 2 bandwidth 809Kbit besteffort triple-isolate nonat nowash ack-filter-aggressive split-gso rtt 100.0ms atm overhead 10 
 Sent 51027233 bytes 98603 pkt (dropped 13191, overlimits 207440 requeues 0) 
 backlog 10773b 18p requeues 0
 memory used: 96064b of 4Mb
 capacity estimate: 809Kbit
 min/max network layer size:           40 /    1478
 min/max overhead-adjusted size:      106 /    1643
 average network hdr offset:           14

                  Tin 0
  thresh        809Kbit
  target         22.3ms
  interval      117.3ms
  pk_delay      124.7ms
  av_delay       42.9ms
  sp_delay        7.4ms
  backlog        10773b
  pkts           111812
  bytes        61481753
  way_inds         6963
  way_miss         1430
  way_cols            0
  drops           10575
  marks               0
  ack_drop         2616
  sp_flows            4
  bk_flows            8
  un_flows            0
  max_len          2984
  quantum           300

**Comment by moeller0** [comment]
>When settled bandwidth is for internet , so we don't need to set mpu.
When settled bandwidth is for ethernet , we need to consider mpu.

You need to set the MPU, if the link you are trying to shape for/on has mpu requirements. Most links like GPON, DOCSIS, PTM do, but ADSL[1|2|2+] as far as I can tell do not.
The telltale sign of requiring MPU is if a technology carries the ethernet frame check sequence in its own packages (as that will drag in the ethernet MPU).

**Comment by yutayu** [comment]
Does that mean it depends on internet connection what I want to shape?

**Comment by yutayu** [comment]
I got it. Thanks.

**Comment by yutayu** [comment]
I use pppoa through ethernet.
Then my recognization is
According to Allowed Packet Lengths of https://wiki.wireshark.org/Ethernet,
0 bytes tcp ack packet costs 46 bytes .
Then mpu is 46.

Is this correct?

**Comment by yutayu** [comment]
or I need to add pppoa overhead 10?
mpu 56

or I need to consider ethernet overhead ?
mpu 64

**Comment by yutayu** [comment]
Just my confusing . hold on . Excuse me.

**Comment by moeller0** [comment]
None of the above ;) For PPPoA over VC/Mux RFC-2364 there is no specific MPU required. The normal ATM cell correction will make sure that 53 is going to be the smallest packet size. So things should just work. BUT really smal packets are typically rare enough that over estimating tad configuring the true MPU will only have a small bandwidth cost and will certainly not causing additional delays.

**Comment by yutayu** [comment]
PPPoA - LAN - cake PC.

Lowest sending UDP packet size is = 28 ( law data 0bytes + IP header 20bytes+ UDP header 8 bytes )
In the other hand , according to https://wiki.wireshark.org/Ethernet , Ethernet fills 46bytes as maximum. 
Then padding on ethernet is 18 bytes ( 46 - 28 ), in this case.

Question.
We need to consider this 18 bytes on PPP ? 
If No, This packets costs 1 ATM = 53 bytes ( 48 + 5 ). then I don't set mpu.
If Yes, This packets costs 2 ATM = 106 bytes ( 2 ( 48 + 5 ). then I will consider mpu for 2 ATM.

This is my asking.

**Comment by yutayu** [comment]
https://networkengineering.stackexchange.com/questions/53489/ethernet-padding-value
https://tools.wordtothewise.com/rfc/rfc948

      IEEE 802.3 packets have minimum size restrictions based on network
      bandwidth.  When necessary, the data field should be padded (with
      octets of zero) to meet the 802.3 minimum frame size requirements.
      This padding is not part of the IP packet and is not included in
      the total length field of the IP header.

This is asking and answer.
Sorry for wasting your time.
Thank you very much.

I don't need to set mpu. :)
