### ISSUE TITLE
Implement ACK prioritization

### ISSUE THREAD

**Issue by ckkcc** [dtaht/sch_cake#131]
ACK prioritization would benefit asymmetric connections. Presumably it's not too difficult since it could reuse some of the ACK filtering code?

https://www.bufferbloat.net/projects/bloat/wiki/ACK_prioritization/

**Comment by chromi** [comment]
TCP acks are already effectively prioritised because they are small packets.  The ack filter further improves performance in practice, by reducing the number of acks that need to get through.

**Comment by moeller0** [comment]
I am not sure that the somewhat ancient, prioritize all ACKs indiscriminately approach, ever was really good advice to begin with. IMHO in a tiered priority scheduler ACKs should be kept inside their respective data packet's priority tier. fq_codel's and cake's sparse flow "boosting" does pretty much that by a somewhat simpler heuristic even inside a priority tier.

**Comment by dtaht** [comment]
yea, I should nuke that old page. ack prioritization needs to die.
