### ISSUE TITLE
qdisc_tree_reduce_backlog appears from 4.1.28 not 4.1.27

### ISSUE THREAD

**Issue by odkrys** [dtaht/sch_cake#132]
https://github.com/dtaht/sch_cake/blob/787329d00b5ad5ad1cbd772460ed99f12d762a1a/cobalt_compat.h#L145

check please.

**Comment by tohojo** [comment]
odkrys <notifications@github.com> writes:

> https://github.com/dtaht/sch_cake/blob/787329d00b5ad5ad1cbd772460ed99f12d762a1a/cobalt_compat.h#L145
>
> check please.

What's the bug? This is expected...

**Comment by odkrys** [comment]
it should be 
```
(KERNEL_VERSION(4,  1, 28) > LINUX_VERSION_CODE)
or
(KERNEL_VERSION(4,  1, 27) >=  LINUX_VERSION_CODE)
```
there is no qdisc_tree_reduce_backlog at Kernel 4.1.27.

**Comment by tohojo** [comment]
odkrys <notifications@github.com> writes:

> it should be (KERNEL_VERSION(4,  1, 28)
> there is no qdisc_tree_reduce_backlog at Kernel 4.1.27.

Oh, I see what you mean; yeah, seems there's an off-by-one error there...
