### ISSUE TITLE
__tcp_hdrlen appears from 4.1.50

### ISSUE THREAD

**Issue by odkrys** [dtaht/sch_cake#134]
https://github.com/dtaht/sch_cake/blob/a5dccfd869afa2026ff7f9c4e431ff2c8e5d53c5/cobalt_compat.h#L90

https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.1.50
```
commit 849bc5e7fd15a0752ef69cf1d59dbcc2569961c8
Author: Craig Gallek <kraig@google.com>
Date:   Wed Feb 10 11:50:37 2016 -0500

    tcp: __tcp_hdrlen() helper
    
    [ Upstream commit d9b3fca27385eafe61c3ca6feab6cb1e7dc77482 ]
    
    tcp_hdrlen is wasteful if you already have a pointer to struct tcphdr.
    This splits the size calculation into a helper function that can be
    used if a struct tcphdr is already available.
    
    Signed-off-by: Craig Gallek <kraig@google.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>
    Signed-off-by: Sasha Levin <alexander.levin@microsoft.com>
```
I got an error in kernel 4.1.51 and checked it.
I haven't checked between 4.1.50 and 4.4.114.

**Comment by tohojo** [comment]
Why are you running these 4.1 kernels? That series is no longer supported upstream, so not terribly inclined to spend a lot of time supporting it here either. If you want the compat layer fixed, please open a pull request...

**Comment by odkrys** [comment]
For asus routers. RT-AC86U is running 4.1.27 and RT-AX88U is running 4.1.51.

It's enough to fix it personally and use it, but there was an error, so I left an issue.
