### ISSUE TITLE
Least Effort PHB (Bulk) is redefined in RFC8622 adding the DSCP Code Point LE.

### ISSUE THREAD

**Issue by RavenWing71** [dtaht/sch_cake#138]
As of June 2019, the Least Effort per-hop behavior had it's DSCP Code Point changed from hijacking CS1 to an official IANA allocation.  The Least Effort PHB now uses the Code Point LE, defined as '000001'

**Comment by chromi** [comment]
> On 26 Jun, 2020, at 7:31 pm, RavenWing71 <notifications@github.com> wrote:
> 
> As of June 2019, the Least Effort per-hop behavior had it's DSCP Code Point changed from hijacking CS1 to an official IANA allocation. The Least Effort PHB now uses the Code Point LE, defined as '000001'

Dude, we just closed an issue on this very subject, six and a half hours ago, by upstreaming a patch.

 - Jonathan Morton
