### ISSUE TITLE
Router and PC behind Router Tin comparing.

### ISSUE THREAD

**Issue by yutayu** [dtaht/sch_cake#148]
Router
tc -st qdisc show dev eth0
qdisc cake 8079: root refcnt 2 bandwidth 809Kbit diffserv3 dual-srchost nonat nowash ack-filter-aggressive split-gso rtt 30.0ms atm overhead 10 
 Sent 64640015 bytes 338336 pkt (dropped 9916, overlimits 182413 requeues 0) 
 backlog 0b 0p requeues 0
 memory used: 124352b of 4Mb
 capacity estimate: 809Kbit
 min/max network layer size:           39 /    1478
 min/max overhead-adjusted size:      106 /    1643
 average network hdr offset:           14

                   Bulk  Best Effort        Voice
  thresh       50560bit      809Kbit    202248bit
  target        362.2ms       22.6ms       90.5ms
  interval      724.4ms       51.1ms      181.1ms
  pk_delay          0us        4.3ms          0us
  av_delay          0us        343us          0us
  sp_delay          0us         14us          0us
  backlog            0b           0b           0b
  pkts                0       348252            0
  bytes               0     67311175            0
  way_inds            0         2394            0
  way_miss            0        23707            0
  way_cols            0            0            0
  drops               0         2103            0
  marks               0            0            0
  ack_drop            0         7813            0
  sp_flows            0            2            0
  bk_flows            0            1            0
  un_flows            0            0            0
  max_len             0         2984            0
  quantum           300          300          300

qdisc ingress ffff: parent ffff:fff1 ---------------- 
 Sent 624571913 bytes 500770 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0

PC

tc -s qdisc show dev eno1
qdisc cake 8013: root refcnt 2 bandwidth 99500Kbit diffserv3 triple-isolate nonat nowash ack-filter-aggressive split-gso rtt 1.0ms noatm overhead 38 mpu 84 
 Sent 31474530 bytes 284753 pkt (dropped 0, overlimits 2255 requeues 0) 
 backlog 0b 0p requeues 0
 memory used: 13640b of 4Mb
 capacity estimate: 99500Kbit
 min/max network layer size:           28 /    1500
 min/max overhead-adjusted size:       84 /    1538
 average network hdr offset:           14

                   Bulk  Best Effort        Voice
  thresh       6218Kbit    99500Kbit    24875Kbit
  target          2.9ms        182us        730us
  interval        5.8ms        1.1ms        1.7ms
  pk_delay          0us         14us          6us
  av_delay          0us          3us          2us
  sp_delay          0us          1us          1us
  backlog            0b           0b           0b
  pkts                0       283036         1717
  bytes               0     31310341       164189
  way_inds            0           16            0
  way_miss            0         1834            9
  way_cols            0            0            0
  drops               0            0            0
  marks               0            0            0
  ack_drop            0            0            0
  sp_flows            0            1            0
  bk_flows            0            1            0
  un_flows            0            0            0
  max_len             0         3748          590
  quantum           300         1514          759

qdisc ingress ffff: parent ffff:fff1 ---------------- 
 Sent 612883973 bytes 441611 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0

My router cake doesn't categorize voice packets sent from my PC and that is categorized as voice packets.

**Comment by dtaht** [comment]
Voip traffic is generally indistinguishable from "sparse" traffic - the sp_flows metric - which is hard to hold a number to as it is so sparse. IF you wish to classify using dscp markings from the client, or an iptables rule (typically from an accepted range of udp port numbers), you can force those packets into the voice class, but by and large, sparse is sparse, and additional classification unnessessary.

**Comment by yutayu** [comment]
@dtaht 
Thanks.
