### ISSUE TITLE
Won't compile on openwrt

### ISSUE THREAD

**Issue by antoinedeschenes** [dtaht/sch_cake#15]
Don't have the time to look into it, but I get the following error trying to compile the latest cake on openwrt trunk for the Archer C7v2:
/tmp/openwrt/build_dir/target-mips_34kc_musl-1.1.11/linux-ar71xx_generic/sched-cake-2015-git/codel5.h:62:27: fatal error: codel5_compat.h: No such file or directory

**Comment by DespairFactor** [comment]
You are just missing that header file it is referencing. 

tmp/openwrt/build_dir/target-mips_34kc_musl-1.1.11/linux-ar71xx_generic/sched-cake-2015-git/codel5.h:62:27: fatal error: <b>codel5_compat.h</b>: No such file or directory

Perhaps this may help: https://github.com/dtaht/sch_cake/commit/98cced08feed668f64eaa17a639eefb78032f5c8

**Comment by tohojo** [comment]
Should be fixed in newest trunk, and in ceropackages.
