### ISSUE TITLE
Tc replace command doesn't change diffserv classify with cake.

### ISSUE THREAD

**Issue by yutayu** [dtaht/sch_cake#156]
When I want to change diffserv4 to 3, tc  replace command doesn't change it.

Before
tc qdisc replace dev "$dev" handle 1: root cake diffserv4 dual-srchost nat bandwidth "$upload" bridged-ptm mpu 64 ack-filter nowash

After
tc qdisc replace dev "$dev" handle 1: root cake diffserv3 dual-srchost nat bandwidth "$upload" bridged-ptm mpu 64 ack-filter nowash

**Comment by tohojo** [comment]
Works for me:

$ sudo tc qdisc replace dev testns handle 1: root cake diffserv4 dual-srchost nat bandwidth 100kbit bridged-ptm mpu 64 ack-filter nowash
$ tc qdisc show dev testns
qdisc cake 1: root refcnt 9 bandwidth 100Kbit diffserv4 dual-srchost nat nowash ack-filter split-gso rtt 100ms ptm overhead 22 mpu 64 
$ sudo tc qdisc replace dev testns handle 1: root cake diffserv3 dual-srchost nat bandwidth 100kbit bridged-ptm mpu 64 ack-filter nowash
$ tc qdisc show dev testns
qdisc cake 1: root refcnt 9 bandwidth 100Kbit diffserv3 dual-srchost nat nowash ack-filter split-gso rtt 100ms ptm overhead 22 mpu 64 

What version of cake and tc are you using where it doesn't work?

**Comment by yutayu** [comment]
modinfo sch_cake
filename:       /lib/modules/6.1.21-v8+/kernel/net/sched/sch_cake.ko.xz
description:    The CAKE shaper.
license:        Dual BSD/GPL
author:         Jonathan Morton
srcversion:     7B4511C6439FAED7C93D676
depends:        
intree:         Y
name:           sch_cake
vermagic:       6.1.21-v8+ SMP preempt mod_unload modversions aarch64

Excuse me. Raspberry pi OS uses maybe old cake like Debian stable.
