### ISSUE TITLE
Told router is too old to leverage Cake on WireGuard VPN patch

### ISSUE THREAD

**Issue by privacyguy123** [dtaht/sch_cake#158]
How do I find out if this is true or not? I'm not able to discern what version of ```cake``` I have on my asuswrt-merlin router - I know for sure ```cake``` is in there and it's an available option but I do notice that it does not seem to recognise the ```flows nonat``` setting on a WireGuard interface and doesn't correctly apply any QoS on a VPN tunnel. Is there a way for me to update this to a version of ```cake``` with this patch installed?

Any help/guidance is appreciated. :)

**Comment by tohojo** [comment]
privacyguy123 ***@***.***> writes:

> How do I find out if this is true or not? I'm not able to discern what
> version of ```cake``` I have on my asuswrt-merlin router - I know for
> sure ```cake``` is in there and it's an available option but I do
> notice that it does not seem to recognise the ```flows nonat```
> setting on a WireGuard interface and doesn't correctly apply any QoS
> on a VPN tunnel. Is there a way for me to update this to a version of
> ```cake``` with this patch installed?

To use this with wireguard you need the support in both wireguard itself
and in sch_cake. The former went into kernel 5.7 and the latter in 5.8.
So if your router is running a kernel older than 5.8, this feature will
not be available.

**Comment by privacyguy123** [comment]
> privacyguy123 ***@***.***> writes:
> How do I find out if this is true or not? I'm not able to discern what version of ```cake``` I have on my asuswrt-merlin router - I know for sure ```cake``` is in there and it's an available option but I do notice that it does not seem to recognise the ```flows nonat``` setting on a WireGuard interface and doesn't correctly apply any QoS on a VPN tunnel. Is there a way for me to update this to a version of ```cake``` with this patch installed?
> To use this with wireguard you need the support in both wireguard itself and in sch_cake. The former went into kernel 5.7 and the latter in 5.8. So if your router is running a kernel older than 5.8, this feature will not be available.

Yikes, that's super new. What routers that you can flash with *wrt even run a kernel that new?

It can never be made to work with say kernel 4.19 or 5.10?

**Comment by tohojo** [comment]
privacyguy123 ***@***.***> writes:

> Yikes, that's super new.

5.8 was released in August 2020, so it's not *that* new.

> What routers that you can flash with *wrt even run a kernel that new?

OpenWrt 22.03 is 5.10 for all targets, 23.05 is 5.15. So anything
supported by OpenWrt? :)

**Comment by privacyguy123** [comment]
> privacyguy123 ***@***.***> writes:
> Yikes, that's super new.
> 5.8 was released in August 2020, so it's not *that* new.
> What routers that you can flash with *wrt even run a kernel that new?
> OpenWrt 22.03 is 5.10 for all targets, 23.05 is 5.15. So anything supported by OpenWrt? :)

Right, I misunderstood the numbering completely. 5.8 is not newer than 5.10 lol.
