### ISSUE TITLE
sqm mode

### ISSUE THREAD

**Issue by dtaht** [dtaht/sch_cake#18]
I would like a 3 tin shaper more exactly equivalent to how sqm works today on fq_codel. My measurements showed that we spend a significant amount of cpu searching through 4 tins, and I have yet to have seen any real advantage to having more than 3.

**Comment by moeller0** [comment]
Hi Dave,

> On Apr 13, 2016, at 22:11 , Dave Täht notifications@github.com wrote:
> 
> I would like a 3 tin shaper more exactly equivalent to how sqm works today on fq_codel. My measurements showed that we spend a significant amount of cpu searching through 4 tins, and I have yet to have seen any real advantage to having more than 3.

```
So you see noticeable more “load” for diffserv8 versus diffserv4, and more for diffserv4 than besteffort? If not I would assume that sqm3 would be just as expensive as diffserv4. I do fully endorse the idea of getting sqm3 implemented in cake though, as it will make comparison much easier.
```

Best Regards
    Sebastian
