### ISSUE TITLE
if you are looking for other models to emulate

### ISSUE THREAD

**Issue by dtaht** [dtaht/sch_cake#19]
There is cisco's std wifi qos ( first link: http://blog.cerowrt.org/post/how_cisco_does_wifi_qos/ )

there is also more of the "strict priority queue" of pfifo_fast (which I regard as a bad idea, but)...

and the dual-queue idea of a separate ect(1) codepoint.

**Comment by chromi** [comment]
I tried to understand the Cisco model, and failed miserably.  This probably means it's too complicated to be useful in practice.
