### ISSUE TITLE
It seems kvfree() is available from 3.15 onward, I needed the change below to compile under opensuse13.2 and ubuntu 14.04, maybe this is required generally?

### ISSUE THREAD

**Issue by moeller0** [dtaht/sch_cake#2]
commit d6a0463769b59e9f3571c6eb59139bae818e0d6a
Author: Sebastian Moeller moeller0@gmx.de
Date:   Thu Jul 23 14:53:53 2015 +0200

```
[sch_cake] kvfree seems reachable for linux kernels >= 3.15

Signed-off-by: Sebastian Moeller <moeller0@gmx.de>
```

diff --git a/codel5.h b/codel5.h
index 0e1509c..41dacc9 100644
--- a/codel5.h
+++ b/codel5.h
@@ -67,6 +67,16 @@ static inline u32 reciprocal_scale(u32 val, u32 ep_ro)
        return (u32)(((u64) val \* ep_ro) >> 32);
 }

+static inline void kvfree(const void *addr)
+{
-  if (is_vmalloc_addr(addr))
-    vfree(addr);
-  else
-    kfree(addr);
  +}
  +
  +
  +
  # endif
  # if LINUX_VERSION_CODE <= KERNEL_VERSION(3,17,0)
  
  @@ -98,14 +108,6 @@ static inline void qdisc_qstats_drop(struct Qdisc *sch)
  sch->qstats.drops++;
  }

-static inline void kvfree(const void *addr)
-{
-  if (is_vmalloc_addr(addr))
-    vfree(addr);
-  else
-    kfree(addr);
  -}
  -
  #define codel_stats_copy_queue(a,b,c,d) gnet_stats_copy_queue(a,c)
  #define codel_watchdog_schedule_ns(a,b,c) qdisc_watchdog_schedule_ns(a,b)
  #else

P.S.: Not sure whether this is the right way to propose this change...

**Comment by DespairFactor** [comment]
I have kvfree on 3.10.40+ your best bet is to fork the repo and send him a pull request.

**Comment by moeller0** [comment]
Well,

as far as http://lxr.free-electrons.com/ident?i=kvfree tells me, there is a kvfree since 3.5 or before. But until before 3.15 it lived under security/apparmor/lib.c. In 3.15 it moved to mm/util.c. My current hypothesis is that the mm version gets dragged in via nested/linked includes somehow, while the app armor version was not. Either that or that opens use and ubntu declare kvfree as static while mainline does not... Anyways, the above patch allows compilation to succeed under some distribution kernels...

In your case, does compilation of sch_cake work out of the box under 3.10.40, I wonder?

Best Regards
        M.

**Comment by DespairFactor** [comment]
Actually, come to think of it, I think I had to comment out the kvfree because it was already defined elsewhere. I will have to remove that to see where it is again. Keep in mind, I am building for android.

**Comment by DespairFactor** [comment]
Look here, this is where I commented it out. I will remove the comment later and see where it is declared, it was a re-declaration error during compile. We may need to make that version filter on the lower version end too and check if it's already defined elsewhere.

https://github.com/DespairFactor/N6/commit/c4e32c8c1252ba1bc5c38c946d5354425f6d284d

**Comment by moeller0** [comment]
I assume that the guards in codel5.h are really only reliable for kernels actually tested... (anybody using > 3.18 will not get any of functions from codel5.h and hence will not encounter double definition errors). I guess I should not have looked at the kernel source to figure out when kvfree appeared, but just move it to a <= 3.15 guard define, since 3.16 was all I tested... But if you can confirm that it works with 3.10 and test that we can and should put the guard at 3.10 (even though it would be good having people test versions between 3.10 and 3.16 as well)

Best Regards
        M.

**Comment by DespairFactor** [comment]
Here it is in my source;) 
https://github.com/DespairFactor/N6/blob/0d54562208e036ad2350c6f103c408a72ae304f9/mm/util.c#L388

Here is extern declaration
https://github.com/DespairFactor/N6/blob/master/include/linux/mm.h#L334

**Comment by moeller0** [comment]
It looks like your android kernel diverged from mainline... not sure what that means regarding the defines in codel5.h. Probably that it will be hard to find a set of defines that work universally...

Best Regards
        M.

**Comment by DespairFactor** [comment]
Yes, android always does diverge from mainline, OEMs often add their own crap, I just wasn't sure it was that deep down that they change the kernel

Regardless, add your guard based on your research, I can just modify mine:)
