### ISSUE TITLE
diffserv-llt

### ISSUE THREAD

**Issue by dtaht** [dtaht/sch_cake#21]
There is of course, no guaruntee that these new codepoints will get through the ietf. I should also go looking for any suggestions of a "LE" least effort codepoint or other historical codepoints we do not map.

I am curious however, if it makes sense to add support for Lo/La across all of cake's diffserv models, if they don't already map?

**Comment by chromi** [comment]
If they do appear in an actual RFC, rather than just an I-D, it might be sensible to map them more generally.  Until then, I suggest not doing so.
