### ISSUE TITLE
New instability with the instability fix

### ISSUE THREAD

**Issue by ldir-EDB0** [dtaht/sch_cake#24]
Hi Jonathan,

This is early warning, I've no further info beyond bba7b5385a3c460c35bb1826ab9599b806f44fa7 caused my router to stop responding to pings, even on local lan very shortly after boot.  It hadn't crashed as heartbeat still going but something was up.  It could be a dodgy build or anything really.  Unfortunately I'm just off to work so had to quickly revert before dashing out the door.

Kevin

**Comment by Schabram** [comment]
Cake with qdisc_tree_reduce_backlog cause this problem <4.4.11 kernel dont have this problem.
Sometime few hours with many traffic +1TB no problem then crash without any usable log, only kernel restart fix it(reboot), unload module is not enough. Crash is random.
Only tried the lede 4.4.11 kernel with backport

EDIT: the problem is deeper not just your resent changes

**Comment by chromi** [comment]
> On 27 May, 2016, at 07:35, trismo notifications@github.com wrote:
> 
> Cake with qdisc_tree_reduce_backlog cause this problem <4.10.11 kernel dont have this problem.

Right.  Clearly I need to collect that size information more accurately, which will be a whole lot easier once I’m using COBALT.
- Jonathan Morton

**Comment by ldir-EDB0** [comment]
I've had a little bit more time to play and I'm no longer convinced this is entirely or at all a cake issue.  My Archer C7 exhibited this strange apparent 'lock up' on reboot even with sqm disabled and also with the latest commit reverted.  Unfortunately I'm unable to get a serial console on the router to see what's going on, however everything else about the router other than wireless network appears ok (ie. system heartbeat, leds active)  LEDE recently updated the wireless backports....I've my suspicions ;-) From my perspective, please feel free to close this report.
