### ISSUE TITLE
Licence info missing

### ISSUE THREAD

**Issue by RubenKelevra** [dtaht/sch_cake#29]
Currently cake taints the kernel because a licence is missing...

> sch_cake: module license 'unspecified' taints kernel

**Comment by ldir-EDB0** [comment]
From sch_cake.c:

module_init(cake_module_init)
module_exit(cake_module_exit)
MODULE_AUTHOR("Jonathan Morton");
MODULE_LICENSE("Dual BSD/GPL");
MODULE_DESCRIPTION("The Cake shaper. Version: " CAKE_VERSION);

**Comment by RubenKelevra** [comment]
Actually I really don't know how this works, but I just compiled it some days ago and it show up this message.

**Comment by dtaht** [comment]
There are a few other potential causes of that problem, notably signed builds will object to out of tree kernel builds. I'm going to put this down to "not a problem", and close this.
