### ISSUE TITLE
Can't unload act_mirred/sch_cake

### ISSUE THREAD

**Issue by sixtyfive** [dtaht/sch_cake#35]
Hi! Is there a trick how one can get the `act_mirred` & `sch_cake` modules unloaded? Not even `rmmod --force` will work and I can't figure out what exactly is still using them. Various invocations of `tc qdisc del` never manage to actually `del` anything, either. Removing the interface (`ip link del dev`) does work but isn't enough in getting the modules unloaded.

**Comment by chromi** [comment]
> On 21 Oct, 2016, at 14:54, J. R. Schmid notifications@github.com wrote:
> 
> Hi! Is there a trick how one can get the act_mirred & sch_cake modules unloaded? Not even rmmod --force will work and I can't figure out what exactly is still using them. Various invocations of tc qdisc del never manage to actually del anything, either…

It is necessary to remove all uses of each module before it can be unloaded.  The following commands should suffice, if run on each relevant interface:

```
sudo tc qdisc del dev $IFACE root
sudo tc qdisc del dev $IFACE ingress
```

Follow them with:

```
modprobe -r sch_cake
modprobe -r act_mirred
```

It works for me...
- Jonathan Morton

**Comment by sixtyfive** [comment]
Jonathan, thank you! That was indeed what was missing! Regards, Jonathan
