### ISSUE TITLE
sqm mode

### ISSUE THREAD

**Issue by dtaht** [dtaht/sch_cake#37]
I really think a three tier sqm mode is enough. More complexity is generally not needed.

**Comment by chromi** [comment]
Which DSCPs do you think should go in each tin, then?  Presumably you’re thinking of bulk, best-effort and latency-sensitive, but what counts as the latter?

 - Jonathan Morton

**Comment by dtaht** [comment]
Bulk: CS1 only
Priority: IMM, EF # and yea we could debate a few others, but really, all I ever see in the real world is IMM

and 25% prio max, 25% bulk min

**Comment by chromi** [comment]
I’m confused as to which DSCP is “IMM”.  I see reference to a “TOS IMM bit” which is most likely the “Minimise Delay” one (TOS4), but also an “Immediate” precedence code which corresponds to CS2.

I think I would argue for including CS6 and CS7 as well; the former is used at least by NTP, which is a legitimate use for it.

 - Jonathan Morton

**Comment by dtaht** [comment]
My issue with CS6 is BGP uses it, which makes for kind of a lose with a 25% cap. Various other documents point to CS7 as something that should be dropped when trying to exit your network.

openssh uses # define IPTOS_LOWDELAY          0x10

for interactive traffic.

**Comment by dtaht** [comment]
A related thought is to obsolete "precedence" for "sqm".

**Comment by chromi** [comment]
> On 28 Nov, 2016, at 02:57, Dave Täht <notifications@github.com> wrote:
> 
> My issue with CS6 is BGP uses it, which makes for kind of a lose with a 25% cap.

Most Cake users won’t care a whit about BGP.  In any case, it’s not a hard cap at 25%; if there is spare bandwidth, it’ll be made available.

> Various other documents point to CS7 as something that should be dropped when trying to exit your network.

Funny, I’d have thought BGP would be a prime candidate for CS7 classification, aka “Net Control".  As it is, I might adjust Cake to treat ARP packets (which don’t have a Diffserv field, not being IP) as if they were CS7.

> openssh uses # define IPTOS_LOWDELAY 0x10 for interactive traffic.

I believe that’s TOS4.

 - Jonathan Morton

**Comment by moeller0** [comment]
> Various other documents point to CS7 as something that should be dropped when trying to exit your network.

Why not compartmentalize CS7 into its own highest priority tin (with a tight _hard_ bandwidth limit, so drop on overuse) allowing people to use cake shapers inside a DSCP-domain, but at the same time making abuse hard. I believe the argument for dropping CS7 on ingress is that according to the RFCs these packets arguably should never have exited their home DSCP-domain. I am (without being burdened by to much RFC reading and pesky things like facts) not convinced that this drop policy is actually any better than re-map to zero in ingress...




> Funny, I’d have thought BGP would be a prime candidate for CS7 classification, aka “Net Control". As it is, I might adjust Cake to treat ARP packets (which don’t have a Diffserv field, not being IP) as if they were CS7.



I believe PPP echo requests and echo replies are also good candidates for the highest priority tier (maybe the same as CS7), a ppp link might go down if a sufficient number of those are either lost or delayed. On a PPP-interface cake will not see these at all, but if cake is instantiated on an ethernet interface that handles e.g. packets for a pppoe link this might be come an issue (even though with a bit of luck the echo ping-pong is sufficiently sparse to profit from sparse flow boosting, but for non-fq).

**Comment by dtaht** [comment]
We already have diffserv-llt for that sebastian. My goal for sqm is to get something directly comparable to the data we have on the sqm-scripts - AND I figure less tins is faster code.

And I'd also like to deprioritize regular icmp by default, too, but that's not easily done here.

**Comment by dtaht** [comment]
I would also argue for treating arp (and nd) without prioritization, or with less prioritization also. Imagine what happens on a mass ping of your entire /64.

**Comment by zcecc22** [comment]
+1 on this simple sqm mode. I run diffserv-llt for its simplicity and great performance and feel a 3 queue approach would be even better. Please keep it simple mapping wise and avoid protocol specific magic :)

**Comment by chromi** [comment]
Here’s what I’ve got in mind at the moment:

/*  Simplified Diffserv structure with 3 tins.
 *		Low Priority		(CS1)
 *		Best Effort
 *		Latency Sensitive	(TOS4, VA, EF, CS6, CS7)
 */

The tin configurations are copied from Diffserv4, minus the Video tin.

I left CS6 and CS7 in deliberately.  Cake doesn’t assume it’s at a Diffserv boundary, and only relies on *standardised* codepoints which are hopefully more likely to retain their meaning across such boundaries.  CS6 is genuinely useful for NTP, and I do plan to map ARP to CS7 because it is a very common “network control” protocol (which is intrinsically non-routeable).

> I would also argue for treating arp (and nd) without prioritization, or with less prioritization also. Imagine what happens on a mass ping of your entire /64.

In that case, Cake’s soft-priority queue saves the day by not permitting the ARPs to outcompete best-effort traffic on more than 25% of the shaped bandwidth.  Yes, it’s still able to trash your VoIP or gaming, but to really fix that we need more tins again.

 - Jonathan Morton

**Comment by dtaht** [comment]
On 12/15/16 1:28 PM, chromi wrote:
> Here’s what I’ve got in mind at the moment:
> 
> /* Simplified Diffserv structure with 3 tins.
> * Low Priority (CS1)
> * Best Effort
> * Latency Sensitive (TOS4, VA, EF, CS6, CS7)
> */
> 
> The tin configurations are copied from Diffserv4, minus the Video tin.
> 
> I left CS6 and CS7 in deliberately. Cake doesn’t assume it’s at a
> Diffserv boundary, and only relies on *standardised* codepoints which
> are hopefully more likely to retain their meaning across such
> boundaries. CS6 is genuinely useful for NTP, and I do plan to map ARP to
> CS7 because it is a very common “network control” protocol (which is
> intrinsically non-routeable).
> 
>> I would also argue for treating arp (and nd) without prioritization,
> or with less prioritization also. Imagine what happens on a mass ping of
> your entire /64.
> 
> In that case, Cake’s soft-priority queue saves the day by not permitting
> the ARPs to outcompete best-effort traffic on more than 25% of the
> shaped bandwidth. Yes, it’s still able to trash your VoIP or gaming, but
> to really fix that we need more tins again.

OK. (TOS4 is ssh?)

**Comment by chromi** [comment]
> On 16 Dec, 2016, at 00:56, Dave Täht <notifications@github.com> wrote:
> 
> OK. (TOS4 is ssh?)

It does seem to be used by OpenSSH, yes.  It’s the “legacy” codepoint for “Minimum Delay”.  Conversely, I think some SSH clients use CS2.  I could reasonably add that to the list as well, but it gets pretty short shrift in most reputable RFCs.

One unique (so far) feature of the Diffserv-LLT was the adjustments to the Codel parameters to try to differentiate the tins more than just “priority” and “bandwidth share”.  The first two tins probably don’t need adjusting, but tuning the “Latency Sensitive” tin for more aggressive AQM might be worthwhile.

 - Jonathan Morton

**Comment by chromi** [comment]
Okay, we now have a 3-tin mode, and it's even the default.  ARP is treated as CS7 (unconditionally).

All the cobalt-branch features since several months ago are also now promoted to master.

**Comment by dtaht** [comment]
Heh. I was thinking triple-isolate should be the default also.

**Comment by chromi** [comment]
> On 19 Dec, 2016, at 04:23, Dave Täht <notifications@github.com> wrote:
> 
> Heh. I was thinking triple-isolate should be the default also.

And it is.  :-)

 - Jonathan Morton
