### ISSUE TITLE
Cake: High traffic leads to a system lock up and subsequent reboot

### ISSUE THREAD

**Issue by thagabe** [dtaht/sch_cake#44]
Tested with current cake on LEDE. Mvebu platform will hang when there are clients pulling in a lot of bandwidth. I do not have logs to prove this but build that do not include kmod-sched-core, kmod-sched, and kmod-sched-cake do not suffer from this issue. And the reboots seem to be present only when sqm selects a cake script with the cake kernel mod. This is the current version of cake on lede https://github.com/lede-project/source/blob/2e101b5e665204575d9546ac5737fc8d36b715d9/package/kernel/kmod-sched-cake/Makefile

**Comment by ldir-EDB0** [comment]
What options is cake instantiated with? (diffserv/nat/bandwidth etc)
Does this mean you've tested using codel only?

**Comment by thagabe** [comment]
@kdarbyshirebryant I'm sorry I do not use cake in cli mode. I just go to luci-sqm-app and put in my in: out: enabled and selecting "Queuing disciplines useable on this system. After installing a new qdisc, you need to restart the router to see updates!" from fq_codel -> cake and the "Queue setup script" simple.qos -> piece_of_cake.qos works for a while, then the router hangs and reboots. As for the second question for the past 4 months i've been under the impression that fq_codel + piece_of_cake.qos was using cake, however when i found out this wasn't the case and started building images with the suggested "sched-core" ," sched", and (mainly) "kmod-sched-cake" thats when I've started to experience hangs and reboots. my in is about (in: 300570) and (out: 30370) with a very basic system (just the base files with luci and some luci-apps)

**Comment by thagabe** [comment]
Yes definitely sch_cake, I have logged the system but I fail to see anything other than sqm keeps loading cake over and over again. In the span of 10 minutes the router rebooted twice 1) after setting this up https://gist.github.com/teffalump/7227752 and 2) after running 3 4k streams and speed tests. Here are the logs (sorry new to gist) https://gist.github.com/thagabe/0074c1ca35f14a6ca309e15044bc2696
