### ISSUE TITLE
does cake really compile with conntrack under lede?

### ISSUE THREAD

**Issue by dtaht** [dtaht/sch_cake#49]
Could someone merely check this?

````
#if defined(CONFIG_NF_CONNTRACK) || defined(CONFIG_NF_CONNTRACK_MODULE)
bla 
#else
#warn "You really, really, really want conntrack for lede"
#endif
````

**Comment by dtaht** [comment]
Yes, it does. lsmod | grep sch_cake will show it used on lede. still poking into the triple-isolate code...

Still it's annoying not to just know.


diff --git a/sch_cake.c b/sch_cake.c
index 3645a0e..458d3d0 100644
--- a/sch_cake.c
+++ b/sch_cake.c
@@ -67,6 +67,9 @@
 #include <net/netfilter/nf_conntrack_core.h>
 #include <net/netfilter/nf_conntrack_zones.h>
 #include <net/netfilter/nf_conntrack.h>
+#define HAVE_CONNTRACK "w/conntrack"
+#else
+#define HAVE_CONNTRACK "no conntrack"
 #endif
 
 #if (KERNEL_VERSION(4,4,11) > LINUX_VERSION_CODE) || ((KERNEL_VERSION(4,5,0) <= LINUX_VERSION_CODE) && (KERNEL_VERSION(4,5,5) > LINUX_VERSION_CODE))
@@ -2107,4 +2110,4 @@ module_init(cake_module_init)
 module_exit(cake_module_exit)
 MODULE_AUTHOR("Jonathan Morton");
 MODULE_LICENSE("Dual BSD/GPL");
-MODULE_DESCRIPTION("The Cake shaper. Version: " CAKE_VERSION);
+MODULE_DESCRIPTION("The Cake shaper. " HAVE_CONNTRACK " Version: " CAKE_VERSION);

**Comment by ldir-EDB0** [comment]
modinfo module will show module dependencies:

~# modinfo sch_cake
module:		/lib/modules/4.4.52/sch_cake.ko
license:	Dual BSD/GPL
depends:	nf_conntrack

Info could be put in the module description string & in cake_version attribute (for those platforms that strip the description strings out...such as LEDE) but I'm not convinced it's worth the space when you can tell by the dependencies
