### ISSUE TITLE
is the nat option needed on ingress or only egress, with nat? 

### ISSUE THREAD

**Issue by dtaht** [dtaht/sch_cake#50]
What I'd wanted to do was apply the new tunneled skb->hash patch for tunnels in mainline,
but we cannot rely on it being set before nat kicked in. Which is a shame.

        if (flow_mode & CAKE_FLOW_FLOWS) {
                flow_hash = jhash_3words(
                        (__force u32)keys.dst,
                        (__force u32)keys.src ^ keys.ip_proto,
                        (__force u32)keys.ports, q->perturbation);
        }

**Comment by ldir-EDB0** [comment]
We need it on both, assuming that you're interest in de-NATing so you can fair share bandwidth.

On egress we need to know the internal pre-NAT address of the source hosts so we can be fair and ensure one internal host doesn't monopolise bandwidth by creating many flows.

On ingress we need to know the internal pre-NAT address of the destination hosts so we can be fair and ensure one internal host doesn't monopolise the ingress bandwidth by creating many flows.

**Comment by xnoreq** [comment]
What happened to tc filters? Flow has src, dst, nfct-src, nfct-dst etc.

**Comment by dtaht** [comment]
we pretty much bypassed the tc filter subsystem, in favor of something that just worked.

Anyway, I've been trying to come up with a better set of hashing methods, see the cake list for details.
