### ISSUE TITLE
Ingress flag/mode/qdisc

### ISSUE THREAD

**Issue by xnoreq** [dtaht/sch_cake#55]
As shortly discussed on the bloat mailing list [1] it would be awesome to have cake try to "shape" ingress bandwidth.

This could happen through a simple additional ingress parameter.

What would be even more awesome however was if the qdisc itself could simply be added as an ingress qdisc.
Right now, on a typical home router, you either have to redirect ingress traffic to an ifb device to shape the egress on that virtual device, or you shape the egress on the LAN device (where you need something like a prio qdisc to separate Internet from local traffic).
An ingress qdisc could directly be attached to the WAN interface, just like the egress qdisc.

[1] https://lists.bufferbloat.net/pipermail/bloat/2017-March/007896.html

**Comment by chromi** [comment]
> On 25 Mar, 2017, at 20:59, xnoreq <notifications@github.com> wrote:
> 
> What would be even more awesome however was if the qdisc itself could simply be added as an ingress qdisc.

This would indeed be awesome, but it’s not a limitation of Cake itself.  Rather, Linux does not currently permit qdiscs to be attached on ingress, only filters and actions.

 - Jonathan Morton

**Comment by dtaht** [comment]
It certainly has long seemed possible to attach a different qdisc on ingress directly. That said, the mirred technique "just works", is only a little complicated, and we have other fish to free.

**Comment by chromi** [comment]
The real issue, which is why I left this open, is to account for dropped packets in the shaper when running in ingress mode.  So I'm reopening this as a reminder to implement that.

Dave, you once said fairly often that ECN-marked packets "had weight" and that dropped packets might therefore be preferable.  When ingress shaping, I now believe it's the other way around: dropped packets in fact "have weight".

**Comment by xnoreq** [comment]
@dtaht This issue is not primarily about an ingress qdisc, but about "shaping" ingress bandwidth (which could still use the common approach of using an ifb redirected to from WAN ingress).

Consider these measurements with a configured 10 Mbps rate:
1 download connection: WAN 9.4 Mbps in, LAN 9.4 Mbps out
16 download connections: WAN 11.5 Mbps in, LAN 10 Mbps out
160 download connections: WAN 14.9 Mbps in, LAN 10 Mbps out

As you can see, the shaper does its job shaping bandwidth into the LAN, but that's not something I care about at all when doing ingress "shaping".

The "simple" solution to this problem is monitoring bandwidth into the qdisc and then reconfiguring it with a lower bandwidth if the monitored bandwidth exceed the configured limit.
That's what I did: https://lists.bufferbloat.net/pipermail/bloat/2017-March/007895.html

(PS: fixed the link in my first post)

**Comment by xnoreq** [comment]
Additional stats which may be useful to someone (download with N TCP connections plus some noise):

1 connection: 
```
 Sent 37362337 bytes 32874 pkt (dropped 98, overlimits 58106 requeues 0)
backlog 4542b 3p requeues 0
memory used: 105152b of 4Mb
capacity estimate: 10Mbit
                Bulk   Best Effort      Voice
 thresh       625Kbit      10Mbit    2500Kbit
 target        29.1ms       5.0ms       7.3ms
 interval     124.1ms     100.0ms      14.5ms
 pk_delay         0us       7.6ms       1.0ms
 av_delay         0us       5.3ms       571us
 sp_delay         0us       1.4ms       114us
 pkts               0       24723        8252
 bytes              0    37019485      495120
 way_inds           0           0           0
 way_miss           0          72           1
 way_cols           0           0           0
 drops              0          98           0
 marks              0           0           0
 sp_flows           0           0           0
 bk_flows           0           1           0
 un_flows           0           0           0
 max_len            0        1514          60
```
  
16 connections: 
```
 Sent 36434285 bytes 28357 pkt (dropped 3960, overlimits 59402 requeues 0)
backlog 30224b 20p requeues 0
memory used: 347200b of 4Mb
capacity estimate: 10Mbit
                Bulk   Best Effort      Voice
 thresh       625Kbit      10Mbit    2500Kbit
 target        29.1ms       5.0ms       7.3ms
 interval     124.1ms     100.0ms      14.5ms
 pk_delay         0us      48.3ms       1.1ms
 av_delay         0us      23.6ms       597us
 sp_delay         0us       3.7ms       135us
 pkts               0       28085        4252
 bytes              0    42193948      255120
 way_inds           0           3           0
 way_miss           0          60           1
 way_cols           0           0           0
 drops              0        3960           0
 marks              0           0           0
 sp_flows           0           1           0
 bk_flows           0          13           0
 un_flows           0           0           0
 max_len            0        1514          60
```
  
160 connections: 
```
 Sent 36622281 bytes 28321 pkt (dropped 11097, overlimits 64473 requeues 0)
backlog 257324b 170p requeues 0
memory used: 664640b of 4Mb
capacity estimate: 10Mbit
                Bulk   Best Effort      Voice
 thresh       625Kbit      10Mbit    2500Kbit
 target        29.1ms       5.0ms       7.3ms
 interval     124.1ms     100.0ms      14.5ms
 pk_delay         0us     170.6ms       1.1ms
 av_delay         0us     140.3ms       603us
 sp_delay         0us     101.2ms       152us
 pkts               0       35708        3880
 bytes              0    53371659      232800
 way_inds           0        3013           0
 way_miss           0         217           2
 way_cols           0           0           0
 drops              0       11097           0
 marks              0           0           0
 sp_flows           0           0           0
 bk_flows           0         161           0
 un_flows           0           0           0
 max_len            0        1514          60
```

**Comment by xnoreq** [comment]
One more thing:

>Dave, you once said fairly often that ECN-marked packets "had weight" and that dropped packets might therefore be preferable. When ingress shaping, I now believe it's the other way around: dropped packets in fact "have weight".

Right. With egress shaping marked packets of course count towards the egress rate, since they are transmitted unlike dropped packets.

If the ingress bandwidth is to be "controlled" you'd need to also count dropped packets.

In my hack I introduced a second control loop (that measures ingress bandwidth and reconfigures cake with lower bandwidth if ingress bandwidth exceeds the initially configured bandwidth), but maybe this could be prevented if dropped packets were not dropped but instead what I'll call **drop-marked**?
Packets drop-marked would stay in the queues just like normal packets and therefore also count towards the egress rate, but when it came to transmission they'd simply be dropped

I think that would make the ingress bandwidth approach the configured bandwidth.

**Comment by chromi** [comment]
Ingress mode, done right, is now supported in the "cobalt" branch and can be turned on using the "ingress" flag in tc-adv.  A corresponding "egress" keyword explicitly turns it off (for live reconfiguration).

Dogfooding it right now with a game updater that likes to use upwards of 150 webseeds through libtorrent.  Usability is greatly improved without having to manually adjust the bandwidth.

Give it a try.  If it also works for you, I can merge this to master.

**Comment by moeller0** [comment]
Hi Jonathan,

how does ingress mode actually differ from egress mode? Isn't solve the reported problem like an "embankment dam”, where excessive incoming packets “pile” up in front of the shaper? How do you actually solve this while still following codel’s rationale for the drop schedule? Reactivel,y adjusting the shaper bandwidth as xnor proposed, does this really do more than just transiently increase the drop rate? And how does your ingress mode tackle the problem without putting the brakes on incoming streams? These are no rhetorical questions I am genuinely interested to learn what the exact problem was and even more the solutions mechanism…

Best Regards

**Comment by chromi** [comment]
> On 4 Apr, 2017, at 15:28, moeller0 <notifications@github.com> wrote:
> 
> how does ingress mode actually differ from egress mode?

In essence, ingress mode counts dropped packets against the shaper schedule, instead of only delivered packets.  I’m *not* using xnoreq’s suggested workarounds, as they react much more slowly to actual conditions.

The reason for this is that in ingress mode, the relevant bottleneck we’re trying to mitigate is upstream of Cake, rather than in the ideal position downstream of it.  Packets that we drop have already passed through that bottleneck, and must therefore be accounted for in the shaper regardless of whether they are dropped or not.

Not doing so leads easily to the situation where we need to drop more packets to signal continuing congestion, but the packets we’ve already dropped have made Cake believe there is no remaining congestion.  Yes, it can lead to lower throughput, but I’m actually surprised myself by how much of a difference this is making to responsiveness under heavy load.

 - Jonathan Morton

**Comment by moeller0** [comment]
Hi Jonathan,


> On Apr 4, 2017, at 14:40, chromi <notifications@github.com> wrote:
> 
> 
> > On 4 Apr, 2017, at 15:28, moeller0 <notifications@github.com> wrote:
> > 
> > how does ingress mode actually differ from egress mode?
> 
> In essence, ingress mode counts dropped packets against the shaper schedule, instead of only delivered packets. I’m *not* using xnoreq’s suggested workarounds, as they react much more slowly to actual conditions.
> 
> The reason for this is that in ingress mode, the relevant bottleneck we’re trying to mitigate is upstream of Cake, rather than in the ideal position downstream of it. Packets that we drop have already passed through that bottleneck, and must therefore be accounted for in the shaper regardless of whether they are dropped or not.
> 
> Not doing so leads easily to the situation where we need to drop more packets to signal continuing congestion, but the packets we’ve already dropped have made Cake believe there is no remaining congestion. Yes, it can lead to lower throughput, but I’m actually surprised myself by how much of a difference this is making to responsiveness under heavy load.

	Thanks a lot for the explanation. I always believed that shaping egress correctly will also in the long run make ingress behave saner, but thanks to your arguments I see why shaping ingress more tightly makes sense. The upshot of the whole thing I assume, is that with ingress mode one can should be able to go/configure closer to the actual bottleneck bandwidth (one simply needs less slack) making up for the bandwidth lost for the slightly more aggressive dropping. I wonder what effect this will have on a single stream and on say a dozen? This certainly looks like another nice trick in the row of nice tricks you taught cake ;)


Best Regards

**Comment by chromi** [comment]
> On 4 Apr, 2017, at 16:14, moeller0 <notifications@github.com> wrote:
> 
> I wonder what effect this will have on a single stream and on say a dozen?

Well, on ECN-enabled traffic it has no effect whatsoever, and doesn’t need to.  So chalk that up as another win for ECN.

The effect on a single, responsive flow should be quite minimal.  However, as the number of flows increases, and with it the number of dropped packets to keep things under control, throughput will go down.  This is really a natural consequence of doing the dropping on the wrong end of the bottleneck link.

I should be able to measure the effects more precisely soon.

 - Jonathan Morton

**Comment by gamanakis** [comment]
@chromi great job! This greatly improves latency in cases where a torrent user is opening many connections simultaneously or is using Steam to update/download games. I suspect it would help in downloading Windows updates, too.

**Comment by xnoreq** [comment]
I am wondering why no-one has ever done this. I mean, I remember first seeing this problem years ago and any attempts to ask for an improvement was shut down with "you can't do ingress shaping".

Egress shaping never was a problem for me. Htb with sfq, or hfsc .. all worked fine, but trying ingress shaping (with imq back in the day) never worked properly. I can even remember fiddling with shell scripts to reconfigure the bandwidth periodically, but this never worked properly again. Because "you can't do ingress shaping".

I had almost completely forgotten that. For years I have just set a lower bandwidth, which worked for most use cases but wasted bandwidth. Then, with a switch to an openwrt router I could finally use fq_codel, and after some fiddling I rediscovered the problem. Upgraded to lede, switched to cake, shared my complete confusion on the mailing list .. and after remembering the idea of periodically reconfiguring the bandwidth I hacked this directly into cake (abusing the autorate_ingress switch so I wouldn't even have to recompile tc). That's what I have been using for the last couple of days, and it works quite nicely.

@chromi  But **I've just tried the cobalt branch .. and ingress mode works.** Implementation looks very simple too, which is good!

I did some quick tests while measuring ping times and ingress rate.
I did have to lower the bandwidth compared to my hack in order to prevent exceed the link's bandwidth. From my quick tests I could observe that ingress bandwidth can be 1 Mbps higher than the configured bandwidth on a 20 Mbps link.

Compared to my hack, which was probably too sensitive and would only ramp up the bandwidth slowly, the new ingress mode still seems to achieve higher utilization of the configured bandwidth despite the lower bandwidth limit.

I will keep testing. Thank you for implementing this. At last, a linux traffic shaper with an ingress option.

**Comment by markuznw** [comment]
Hello guys, just wanted to ask is there any progress on ingress mode? I've tried it in the brief period it was proposed as PR to lede head and I can say it did wonders on my poor 10/1 adsl line. It was actually finally usable with windows updates and/or torrent based game clients (like blizzard) that are totally melting my line with classic sqm cake. I've read it was reverted for some reported issues so I'm looking forward any progress or easy testing branch :D @kdarbyshirebryant 

Thanks in advance for any response :)

**Comment by chromi** [comment]
I have an update here which should fix or at least mitigate the reported
problem, thus making it suitable for the master branch.  When I'm able to
push it (connectivity trouble), I will.

Meanwhile, you can use the "cobalt" branch to get the ingress feature.
That's where my experiments happen, so pick a stable commit and stick to it
unless you want to help debug stuff that breaks.

- Jonathan Morton

**Comment by chromi** [comment]
The mitigation previously mentioned is now pushed to cobalt.  (I thought I'd already done that sooner.)
