### ISSUE TITLE
linux-next breaks build

### ISSUE THREAD

**Issue by anomeome** [dtaht/sch_cake#57]
commit [fceb6435e852](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=fceb6435e85298f747fee938415057af837f5a8a) ("netlink: pass extended ACK struct to parsing functions") in linux next-20170418+

causes this [error.](http://ix.io/rhh)

**Comment by koenkooi** [comment]
Which is now in the released 4.11.0 kernel.
