### ISSUE TITLE
Should this be "tcph_check"? For the triggering ACK we already check this condition outside the loop

### ISSUE THREAD

**Issue by ricudis** [dtaht/sch_cake#82]
https://github.com/dtaht/sch_cake/blob/5bf0b6596721e18269ee4bae6e3549c75cba923a/sch_cake.c#L1015

**Comment by ldir-EDB0** [comment]
@rmounce thoughts on this one Ryan?

**Comment by rmounce** [comment]
Good catch, that one's my fault. PR created with fix.
