### ISSUE TITLE
Unsigned comparison with < 0 

### ISSUE THREAD

**Issue by ricudis** [dtaht/sch_cake#83]
https://github.com/dtaht/sch_cake/blob/5bf0b6596721e18269ee4bae6e3549c75cba923a/sch_cake.c#L1824

Using a recent compiler, this line emits a warning about unsigned comparison with < 0.

Using the equivalent expression "(now < flow->cvars.drop_next)" avoids the issue

**Comment by ldir-EDB0** [comment]
oooh interesting catch!  The sort of thing that makes you wonder what suddenly starts/stops working as a result of fixing the warning :-)

**Comment by chromi** [comment]
> On 7 Jan, 2018, at 12:56 am, Kevin <notifications@github.com> wrote:
> 
> oooh interesting catch! The sort of thing that makes you wonder what suddenly starts/stops working as a result of fixing the warning :-)

Probably very little effect - but I've fixed it anyway.  That piece of code is just meant to make sure the AQM state has fully decayed to rest before releasing the queue into the free list.

 - Jonathan Morton
