### ISSUE TITLE
Cake classification, classification of ingress

### ISSUE THREAD

**Issue by xnoreq** [dtaht/sch_cake#97]
I'd like to raise this issue again (see #14 and possibly several others).
Without classes, how would you classify incoming packets (where all you can do is restore the connmark with tc action connmark) through an ifb device (see tc action mirred) into "classes" that cake understands?
Currently, this is impossible.

This makes sense because while you can typically control the dscp values of the packets you're sending (and use iptables to connmark those connections), it is not so easy to control incoming packets.

Imagine you have different applications that produce lots of bulk traffic. Not all of them even have the feature to set dscp values.
Much worse however is when the much higher traffic incoming traffic has no dscp value anyway. This results in bulk being mixed with best effort.

There's one workaround I'm aware of that makes this work but it is ugly as instead of the ifb it requires an extra interface, extra qdiscs, etc.

The argument I heard against proper tc classes is simplicity, but this is a bad argument because the average Joe has no clue what dscp is. Also, depending on the application setting a custom dscp value is hard to impossible for the average Joe.

Proper tc classes would make using cake much simpler. Instead of trying to configure applications to send the right dscp or do workarounds, the user could classify based on anything that iptables can do (made arbitrarily simple through router configuration interface).
Iptables would simply connmark and tc would classify based on these fwmarks in _both directions, ingress and egress._

**Comment by tohojo** [comment]
The upstream version has tc class support. See the upstream-4.18 branch. It's a PITA to backport so it works on all old kernel versions, though, so it's not in the cobalt branch...

**Comment by tohojo** [comment]
(Or that should rather be "hopefully-soon-to-be-upstream" version :))

**Comment by xnoreq** [comment]
I was about to say that maybe classes aren't even necessary if there was a switch that would cause it to classify based on fwmark value instead of the dsfield value. Sort of a simple `tin = q->tin_index[cake_handle_fwmark(...`


Did the net sched stuff change that much in the last couple of kernel versions? I'd love to see this on openwrt which runs 4.4.
So how do the classes work, how are they integrated with cake's (diffserv) tins?

**Comment by tohojo** [comment]
xnoreq <notifications@github.com> writes:

> I was about to say that maybe classes aren't even necessary if there
> was a switch that would cause it to classify based on fwmark value
> instead of the dsfield value. Sort of a simple `tin =
> q->tin_index[cake_handle_fwmark(...`

It'll assign diffserv tin based on skb->priority, and queue within that
tin based on classid.

> Did the net sched stuff change that much in the last couple of kernel
> versions? I'd love to see this on openwrt which runs 4.4. So how do
> the classes work, how are they integrated with the diffserv priority
> queues?

Enough that it doesn't compile as-is. No idea how much work it'll take
to backport. Pull requests welcome, otherwise I'll get around to
backporting it once it's been accepted upstream...

**Comment by moeller0** [comment]
On May 25, 2018 6:58:57 PM GMT+02:00, xnoreq <notifications@github.com> wrote:
>I was about to say that maybe classes aren't even necessary if there
>was a switch that would cause it to classify based on fwmark value
>instead of the dsfield value. Sort of a simple `tin =
>q->tin_index[cake_handle_fwmark(...`
>
>
>Did the net sched stuff change that much in the last couple of kernel
>versions? I'd love to see this on openwrt which runs 4.4.

Well, 18.06 is in the process of being released next month with kernel >= 4.9, so backporting to 4.4 might not be necessary...

Best Regards
      Sebastian

>So how do the classes work, how are they integrated with the diffserv
>priority queues? 

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tohojo** [comment]
moeller0 <notifications@github.com> writes:

> On May 25, 2018 6:58:57 PM GMT+02:00, xnoreq <notifications@github.com> wrote:
>>I was about to say that maybe classes aren't even necessary if there
>>was a switch that would cause it to classify based on fwmark value
>>instead of the dsfield value. Sort of a simple `tin =
>>q->tin_index[cake_handle_fwmark(...`
>>
>>
>>Did the net sched stuff change that much in the last couple of kernel
>>versions? I'd love to see this on openwrt which runs 4.4.
>
> Well, 18.06 is in the process of being released next month with kernel
> >= 4.9, so backporting to 4.4 might not be necessary...

Which is one of the reasons I haven't put any effort into backporting
yet ;)

**Comment by tohojo** [comment]
Just pushed a backport of the tc class support down to kernel v4.9. Testing welcome :)

**Comment by fgimenezm** [comment]
From OpenWRT v18.06 release notes it looks like this backport made it to the release.
Where can I find more information about it so I can give it a try?

UPDATE: found details here: https://lists.bufferbloat.net/pipermail/cake/2018-July/004007.html
It appears to work OK for me. Made a tc filter matching a specific port and set priority with skbedit and I see stuff getting sent to the "bulk" tin

**Comment by tohojo** [comment]
Federico Gimenez Molinelli <notifications@github.com> writes:

> From OpenWRT v18.06 release notes it looks like this backport made it to the release.
> Where can I find more information about it so I can give it a try?

This uses the standard 'tc filter' mechanism for classification. Setting
the class ID selects a queue within a diffserv tin, and setting the skb
priority sets the diffserv tin. The priority needs to be set so the
major number matches the cake qdisc ID.

**Comment by xnoreq** [comment]
Doesn't work for me.
```
iptables ... -j CLASSIFY --set-class 1:0
```

should put the packets into qdisc cake 1: first tin ("bulk"), no?

**Comment by tohojo** [comment]
Tin numbers start from 1 (0 meaning "no classification")

**Comment by xnoreq** [comment]
I get an unresponsive system (100% load) with this on a TL-WDR3600:
```
iptables: -A POSTROUTING
-j CONNMARK --restore-mark
-m mark ! --mark 0 -j ACCEPT
-p icmp -j CONNMARK --set-mark 0x07/0xff
```

```
tc qdisc add dev eth0.2 root handle 1: cake bandwidth ${UPRATE}kbit rtt 70ms dual-srchost docsis nat
tc filter add dev eth0.2 parent 1: protocol ip prio 1 handle 0x07 fw flowid 1:3
```

**Comment by tohojo** [comment]
xnoreq <notifications@github.com> writes:

> I get an unresponsive system (100% load) with this on a TL-WDR3600:

Hmm, that ought to work. This is on openwrt, I assume? What happens if
you replace the iptables / fw filter with just a 'matchall' filter?

**Comment by xnoreq** [comment]
iptables -j CLASSIFY works, but as soon as I add the tc filter it locks the system.

I don't think matchall is available on openwrt, or maybe I just need to install some extra package.

PS: Fyi, I have a second instance of cake on ifb0.

**Comment by tohojo** [comment]
xnoreq <notifications@github.com> writes:

> iptables -j CLASSIFY works, but as soon as I add the tc filter it
> locks the system.

What happens if you add the filter without the iptables rule?

> I don't think matchall is available on openwrt, or maybe I just need
> to install some extra package.

Ah, right, it may not be...

**Comment by xnoreq** [comment]
Will test this again tomorrow. 
My idea to do ingress shaping was to tc action connmark restore the ctmark on the ingress ifb, but I haven't even checked if tc-connmark is available in openwrt.

edit: it's in package kmod-sched-connmark

**Comment by tohojo** [comment]
xnoreq <notifications@github.com> writes:

> Will test this again tomorrow.

Right

> My idea to do ingress shaping was to tc action connmark restore the
> ctmark on ifb, but I haven't even checked if tc-connmark is available
> in openwrt.

Ah yes, that would probably work :)

**Comment by xnoreq** [comment]
As soon as the `fw` filter gets matching packets I get a lockup. Last thing I see with `top` is:
```
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
    3     2 root     RW       0   0%  36% [ksoftirqd/0]
```

So:
```
tc filter add dev ifb0 parent 1: protocol all prio 3 \
	handle 0x01 fw flowid 1:1
```
is fine as long as I don't restore the ctmark before that. If I do, I immediately get a lockup. 

Same happens with eth0.2 (egress) fw filter. Iptables CLASSIFY is fine, but as soon as I add an `fw` filter instead, that should do the same thing, I get a lockup.

**Comment by tohojo** [comment]
And how does the lockup happen? Does the tc command hang, or does it return and the system hangs afterwards?

Also, does the same thing happen if you use fq_codel instead of cake?

**Comment by xnoreq** [comment]
The first times I tried the command completely normally but the system slowed over a few seconds to the point where SSH didn't respond anymore, nor did any other service.

The last times this happened almost instantly after adding the filters. So the command seems to complete but then the system is just unresponsive.

I think this is because when I first tested it there was almost no traffic, so very few packets would hit the filter.

**Comment by tohojo** [comment]
xnoreq <notifications@github.com> writes:

> The first times I tried the command completely normally but the system
> slowed over a few seconds to the point where SSH didn't respond
> anymore, nor did any other service.
>
> The last times this happened almost instantly after adding the
> filters. So the command seems to complete but then the system is just
> unresponsive.
>
> I think this is because when I first tested it there was almost no
> traffic, so very few packets would hit the filter.

Right, so it's a traffic processing thing.

Could you please try (a) a different qdisc (e.g., fq_codel), and (b) a
different filter (e.g., u32) and see which combinations fail?

**Comment by xnoreq** [comment]
I get no hangs with fq_codel.

**Comment by xnoreq** [comment]
Hangs with cake:
```
tc filter add dev eth0.2 parent 1: protocol ip prio 2 \
	u32 match icmp type 0 0 flowid 1:3
tc filter add dev eth0.2 parent 1: protocol ip prio 3 \
	u32 match tcp dst 443 0xffff flowid 1:1
```

No hangs with fq_codel.

**Comment by xnoreq** [comment]
One more question, tc filter flowid doesn't actually select the tin, does it?
The code seems to use only the minor flowid (major is ignored?) to select the flow.

To select the tin I'd have to use action skbedit where the minor is now the tin number starting at 1 (major needs to match the qdisc handle), no?

Finally, iptables CLASSIFY does seem to have the same effect as skbedit, but now the major needs to match the qdisc handle?


edit: with skbedit major needs to match as well

**Comment by tohojo** [comment]
xnoreq <notifications@github.com> writes:

> One more question, tc filter flowid doesn't actually select the tin, does it?
> The code seems to use only the minor flowid (major is ignored?) to
> select the flow.

Yeah, flowid / classid overrides cake's hashing and sets the flow. This
ignores the major numer.

> To select the tin I'd have to use action skbedit where the minor is
> now the tin number starting at 1 (and major is again ignored?), no?
>
> Finally, iptables CLASSIFY does seem to have the same effect as
> skbedit, but now the major needs to match the qdisc handle?

To set the tin, you need to set the priority with skbedit (or I guess
classify, or even an application that sets priority will work). In this
case the major number has to match the qdisc ID.

**Comment by fgimenezm** [comment]
In my case I just wanted to use diffserv3 and force a specific app's traffic to "Bulk" (tin 1) while leaving the rest default. I didn't use any iptables rules, I did this instead:

For the ingress side I configured this app to listen on port 8999 and forwarded that on the router. Then I made a copy of layer_cake.qos and added this at the end of the "ingress()" function (it's partially hardcoded... shame on me):

```    # send traffic to port 8999 into bulk tin
    MAJOR=$( $TC_BINARY qdisc show dev $DEV | awk '{print $3}' )
    $TC filter add dev $DEV parent $MAJOR protocol ip prio 20 u32 \
        match ip dport 8999 0xffff action skbedit priority ${MAJOR}1
```
( the ":" needed for the "MAJOR:tin" priority setting is already in the $MAJOR variable)

For the egress side, since the app runs on a Windows machine I configured a QoS policy using Windows' Group Policy Editor. This policy matches the app's executable name and sets DSCP=8 (CS1) to all traffic generated by it. cake's diffserv3 sends CS1 traffic to the bulk tin so marking it this way sends that app's egress traffic to tin 1 without requiring any extra processing on the router.

I monitored the stats with "tc -s" before and after setting each of those and I could see the immediate effect on the numbers. The moment I added the "tc" filter for the ingress the numbers on the bulk tin started to move, and the same happened on egress when I added the Windows QoS policy.
I may need to do more fine tuning but at the moment it feels like it's working ok.

I assume cake will still identify the flows in each tin and do it's magic prioritizing the non-bulk stuff over the bulk stuff, is that correct?

I'm running Openwrt v18.06.0 on a wdr3600.

**Comment by moeller0** [comment]
Dear Frederice,

that sounds quite nice.
I have a question regarding the group policy editor, did you manage to get it to work without a domain/active directory controller? I ask, because the need to properly dscp mark from windows machines comes up quite often, but so far it seemed impossible to do so in a domain controller-less home network...

Best Regards
	Sebastian

**Comment by xnoreq** [comment]
After my question about skbedit yesterday I switched my filters and it's been working since then without any noticeable problems.

So iptables marks the connections, tc fw filter with action skbedit sets the tin.
For ingress, I use tc action connmark first to restore the mark of the connection.

Still strange that a filter with flowid would give me lockups.


@moeller0 You need the following registry hack:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\QoS]
"Do not use NLA"="1"

```
Don't forget to reboot and don't forget to reapply randomly after some Windows updates removed/reverted it.

**Comment by tohojo** [comment]
Right, so setting the priority works, but overriding the flow classification results in a hang?

What kernel version is your device using?

**Comment by xnoreq** [comment]
Linux router 4.9.111 #0 Mon Jul 30 16:25:17 2018 mips GNU/Linux

**Comment by fgimenezm** [comment]
Hmmm... I don't have the "Do not use NLA"="1" registry key, but I could see the numbers for Tin 1 started to move in "tc -s" as soon as I enabled the Policy. I have Windows 10 Pro, maybe that maks a difference? (I don't think the non-Pro versions even have the policy editor)
EDIT: I don't have a domain, it's just a standalone machine.

**Comment by fgimenezm** [comment]
I've just noticed there is a flaw in my logic. The windows policy is marking the packets going out, but the responses to those packets are not marked. I guess I need to use iptables and CONNMARK  after all.

**Comment by fgimenezm** [comment]
Actually, I’m confused now.
If I set CS1 from the source then the SYN will go out through the bulk tin. Is cake then keeping all the traffic going back and forth for that connection in the same tin? Or the decision is done for each packet independently?

**Comment by chromi** [comment]
> On 9 Aug, 2018, at 3:14 am, Federico Gimenez Molinelli <notifications@github.com> wrote:
> 
> If I set CS1 from the source then the SYN will go out through the bulk tin. Is cake then keeping all the traffic going back and forth for that connection in the same tin? Or the decision is done for each packet independently?

That decision is memoryless - it's normally done on the DSCP encoded in each packet.

 - Jonathan Morton

**Comment by fgimenezm** [comment]
I think you are right, the Windows QoS policy is not working as I thought it was. Some packets do get the DSCP but not all of them. It's weird.
The good news is that at least cake + iptables conntrack + tc conntrack + tc sbkedit is sending the marked packets to the right tin.

**Comment by fgimenezm** [comment]
Found the fix for Windows 10 QoS thing. It was in a responde here: https://serverfault.com/questions/769843/cannot-set-dscp-on-windows-10-pro-via-group-policy

The group policy editor creates (and only shows) policies for the "Domain" network profile.
But using powershell you can specify "-NetworkProfile All" to force it to apply to all connections

Now I'm getting all my traffic properly marked and sent to the right Tin.

**Comment by moeller0** [comment]
Hi Federico,


since this is a topic that comes up quite often when supporting users on the openwrt forums, could I ask you to help me write a short description how to set-up egress dscp marking for specific applications under windows, please? Since I do not use windows at home* I really can not test this in a meaningful way, this is why I ask for your help...

Best Regards
	Sebastian


*) I do have a windows 7 VM, but that is not really representative for current windows10 machines, so only a partial testing setup...

**Comment by fgimenezm** [comment]
Sure, I'll write something up. Hopefully I'll have some time for this
tomorrow night.
I have only one Win10 Pro so I'll use that. I think the non-pro versions
don't have the group policy editor and I don't know if the powershell
method works there either, but at least I'll write something for Win10 Pro.

**Comment by fgimenezm** [comment]
@moeller0 , here's my attempt on a short HOWTO for DSCP tagging on windows
[Win-QoS-policies.pdf](https://github.com/dtaht/sch_cake/files/2279887/Win-QoS-policies.pdf)

And here's a simplified version of the layer_cake.qos patch that I'm using (needs the "connmark" packages and diffserv3. Maybe "conntrack extra" packages too but not sure):
```patch
--- layer_cake.qos      2018-08-11 00:33:12.056163000 -0300
+++ my_layer_cake.qos   2018-08-11 00:42:58.676704000 -0300
@@ -41,10 +41,34 @@

     $IP link set dev $DEV up

-    # redirect all IP packets arriving in $IFACE to ifb0
+    # redirect all IP packets arriving in $IFACE to ifb0 restoring connmark in the process

     $TC filter add dev $IFACE parent ffff: protocol all prio 10 u32 \
-       match u32 0 0 flowid 1:1 action mirred egress redirect dev $DEV
+       match u32 0 0 flowid 1:1 action connmark action mirred egress redirect dev $DEV
+
+    # send traffic to bulk based on connmark
+    MAJOR=$( tc qdisc show dev $DEV | head -1 | awk '{print $3}' )
+    tc filter add dev $DEV parent $MAJOR protocol ip prio 20  \
+        handle 0x01 fw action skbedit priority ${MAJOR}1
+
+    # Configure iptables chain to mark packets
+    ipt -t mangle -N QOS_MARK_${IFACE}
+
+    # If packets have DSCP 8 then mark that connection so the response packets are also sent to bulk
+    ipt -t mangle -A QOS_MARK_${IFACE} -p tcp -m dscp --dscp 8 -j MARK --set-mark 0x01/0xff
+    ipt -t mangle -A QOS_MARK_${IFACE} -p udp -m dscp --dscp 8 -j MARK --set-mark 0x01/0xff
+
+    # You can add more rules here. For example, to mark incomming connections on port 9999 tcp/udp
+    # ipt -t mangle -A QOS_MARK_${IFACE} -i $IFACE -p tcp --dport 9999 -j MARK --set-mark 0x01/0xff
+    # ipt -t mangle -A QOS_MARK_${IFACE} -i $IFACE -p udp --dport 9999 -j MARK --set-mark 0x01/0xff
+
+    # save the connmark
+    ipt -t mangle -A QOS_MARK_${IFACE} -j CONNMARK  --save-mark
+
+    # Send unmarked connections to the marking chain
+    ipt -t mangle -A PREROUTING  -i $IFACE -m mark --mark 0x00/0xff -g QOS_MARK_${IFACE}
+    ipt -t mangle -A POSTROUTING -o $IFACE -m mark --mark 0x00/0xff -g QOS_MARK_${IFACE}
+
 }

 sqm_start() {
```

**Comment by xnoreq** [comment]
Regarding the hangs: `cake_hash` updates a bunch of stuff (such as `q->flows`) which is skipped in that case.

Are you guys sure this doesn't need to be updated?

**Comment by tohojo** [comment]
Yeah, you're right. Someone else ran into the same problem before I had a chance to investigate further. There's an ongoing discussion on the mailing list and there will probably be a patch coming soonish :)

**Comment by xnoreq** [comment]
Two more things before this issue can be closed: tc-cake.8 should be updated with the info how skb->priority maps to tins. Wouldn't hurt to mention tc-skbedit either.

The second thing is either re-enabling the flow classification again or removing it completely.
I don't need it because the flow isolation algorithms that are built into cake are sufficient for me, but maybe someone else has different requirements.


I saw a comment about doubts about performance on the mailing list: as was pointed out correctly, cake was already slower than "alternatives" before tin/flow classification was implemented.
This is not what made cake "slow".

**Comment by tohojo** [comment]
xnoreq <notifications@github.com> writes:

> Two more things before this issue can be closed: tc-cake.8 should be
> updated with the info how skb->priority maps to tins. Wouldn't hurt to
> mention tc-skbedit either.

Yeah, I'll write up something for the man page.

> The second thing is either re-enabling the flow classification again
> or removing it completely. I don't need it because the flow isolation
> algorithms that are built into cake are sufficient for me, but maybe
> someone else has different requirements.

I just pushed a change that reinstates the flow classification, and also
makes it possible to override the host classification. Care to test? :)
